### ISSUE TITLE
Tear down and initialization functions

### ISSUE THREAD

**Issue by kingozzy24** [azuqua/convey#1]
Include an option to run initialization and tear down functions when registering services in convey

app.poll(service, channel, interval, initialization)

and 

app.close(service, channel, teardown)

and then 

function initialization(channel, callback) {}
function teardown(channel, callback) {}

**Comment by kevinmctigue** [comment]
This is a possible addition to the API that we'll consider adding

**Comment by kingozzy24** [comment]
Ideally we would have an interface like so 
```

serviceBusService = function() {
  var serviceBus = new ServiceBusClient();

  function init(queueName, done) {
    //do work to initialize the queue named 'queueName'
  }

  function teardown(queueName, callback) {
    //do work to shut down the queue named 'queueName'
  }

  function poll(queueName, dispatch) {
    //poll a queue named 'queueName'
  }

  function push(queueName, body) {
    // push data 'body' to queue named 'queueName'
  }

  return {
    init: init,
    teardown: teardown,
    poll: poll,
    send: push
  }
}

```
and when you declare the service it's like 
```
app.use("serviceName", serviceBusService());
```

**Comment by nikhilhasija** [comment]
+1

**Comment by kevinmctigue** [comment]
This is interesting. Obviously it wouldn't be ```app.use```. I'm thinking ```app.set('service', serviceBusService())```
